/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import ui.main.MainFrame;

//editan buat create
import models.Book;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import utils.TablePopulator;

/**
 *
 * @author Dukhaan
 */
public class AdminHomeView extends javax.swing.JPanel implements TablePopulator {

    /**
     * Creates new form AdminHomeView
     */
    private MainFrame mainFrame;

    public AdminHomeView(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        populateTable();

        bookTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = bookTable.getSelectedRow();
                if (selectedRow != -1) {
                    // Retrieve data from the selected row
                    String title = (String) bookTable.getValueAt(selectedRow, 0);
                    String author = (String) bookTable.getValueAt(selectedRow, 1);
                    double price = (double) bookTable.getValueAt(selectedRow, 2);

                    // Set the values to the corresponding text fields
                    lblTitle.setText(title);
                    lblAuthor.setText(author);
                    lblPrice.setText(String.valueOf(price));
                }
            }
        });
    }

    @Override
    public void populateTable() {
        System.out.println("Populating table...");
        // Get the book list
        List<Book> bookList = this.mainFrame.getStore().getBooks();

        // Populate the table with book data
        DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
        for (Book book : bookList) {
            Object[] rowData = {
                book.getTitle(),
                book.getAuthor(),
                book.getPrice(),};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddNewBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        lblTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEditBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(37, 42, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 426));

        jLabel7.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 224, 224));
        jLabel7.setText("Home");

        lblProfile.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(223, 224, 224));
        lblProfile.setText("Profile");
        lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfileMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(245, 83, 112));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblProfile)
                    .addComponent(lblLogout))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(238, 238, 238)
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jLabel3.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 224, 224));
        jLabel3.setText("Home");

        btnAddNewBook.setBackground(new java.awt.Color(64, 206, 206));
        btnAddNewBook.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnAddNewBook.setForeground(new java.awt.Color(37, 42, 51));
        btnAddNewBook.setText("Add new book");
        btnAddNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewBookActionPerformed(evt);
            }
        });

        bookTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookTable.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        bookTable.setForeground(new java.awt.Color(255, 255, 255));
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Author", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        for(int i = 0; i < bookTable.getColumnCount(); i++) {
            bookTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        jScrollPane1.setViewportView(bookTable);

        lblTitle.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblTitle.setText("Book Title");
        lblTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTitleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel1.setText("Title");

        lblAuthor.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblAuthor.setText("Book Author");
        lblAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAuthorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel2.setText("Author");

        lblPrice.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblPrice.setText("Book Price");
        lblPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPriceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel4.setText("Price");

        btnEditBook.setBackground(new java.awt.Color(255, 167, 117));
        btnEditBook.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnEditBook.setForeground(new java.awt.Color(0, 0, 0));
        btnEditBook.setText("Edit Book");
        btnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setBackground(new java.awt.Color(245, 83, 112));
        btnDeleteBook.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnDeleteBook.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteBook.setText("Delete Book");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddNewBook)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnEditBook)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDeleteBook)))))
                            .addComponent(jLabel4)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Logout
            mainFrame.showView(mainFrame.getLoginView());
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfileMouseClicked
        mainFrame.showView(new AdminProfileView(mainFrame));
    }//GEN-LAST:event_lblProfileMouseClicked

    private void btnAddNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewBookActionPerformed
        // Create an instance of AdminAddBook
        AdminAddBook adminAddBook = new AdminAddBook(mainFrame);

        // Show the AdminAddBook view
        mainFrame.showView(adminAddBook);
    }//GEN-LAST:event_btnAddNewBookActionPerformed

    private void lblTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitleActionPerformed

    private void lblAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAuthorActionPerformed

    private void lblPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPriceActionPerformed

    private void btnEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookActionPerformed
        try {
            // Dapatkan data yang diedit dari kolom teks
            String editedTitle = lblTitle.getText();
            String editedAuthor = lblAuthor.getText();
            double editedPrice = Double.parseDouble(lblPrice.getText());

            int selectedRow = bookTable.getSelectedRow();
            if (selectedRow != -1) {
                // Perbarui buku yang dipilih di tabel
                bookTable.setValueAt(editedTitle, selectedRow, 0);
                bookTable.setValueAt(editedAuthor, selectedRow, 1);
                bookTable.setValueAt(editedPrice, selectedRow, 2);

                List<Book> bookList = mainFrame.getStore().getBooks();
                Book selectedBook = bookList.get(selectedRow);

                selectedBook.setTitle(editedTitle);
                selectedBook.setAuthor(editedAuthor);
                selectedBook.setPrice(editedPrice);

                JOptionPane.showMessageDialog(this, "Edit buku berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Harap pilih buku untuk diedit.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format harga tidak valid. Harap masukkan angka yang valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengedit buku.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

        // Bersihkan kolom teks
        lblTitle.setText("");
        lblAuthor.setText("");
        lblPrice.setText("");
    }//GEN-LAST:event_btnEditBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        int selectedRow = bookTable.getSelectedRow();
        if (selectedRow != -1) {
            // Dapatkan buku yang dipilih dari model tabel
            DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
            String deletedTitle = (String) model.getValueAt(selectedRow, 0);

            // Hapus baris yang dipilih dari tabel
            model.removeRow(selectedRow);

            // Hapus buku yang sesuai dari data model atau struktur data
            List<Book> bookList = mainFrame.getStore().getBooks();
            for (int i = 0; i < bookList.size(); i++) {
                Book book = bookList.get(i);
                if (book.getTitle().equals(deletedTitle)) {
                    bookList.remove(i);
                    break;
                }
            }

            // Tampilkan pesan sukses
            JOptionPane.showMessageDialog(this, "Buku '" + deletedTitle + "' berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Tampilkan pesan kesalahan jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(this, "Harap pilih buku untuk dihapus.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookTable;
    private javax.swing.JButton btnAddNewBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnEditBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblAuthor;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField lblPrice;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JTextField lblTitle;
    // End of variables declaration//GEN-END:variables
}
