/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.reader;

import javax.swing.JOptionPane;
import models.Book;
import models.Reader;
import services.DatabaseService;
import ui.main.MainFrame;

/**
 *
 * @author Dukhaan
 */
public class DetailView extends javax.swing.JPanel {

    /**
     * Creates new form ContentView
     */
    private MainFrame mainFrame;
    private Reader currentReader;
    private Book book;
    private boolean isBookPurchased;

    public DetailView(MainFrame mainFrame, Book book) {
        initComponents();
        this.mainFrame = mainFrame;
        this.currentReader = (Reader) DatabaseService.getCurrentUser();
        this.book = book;
        isBookPurchased = setButtonAction();
        setDetailTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblWishlist = new javax.swing.JLabel();
        lblLibrary = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JTextField();
        lblPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JTextField();
        btnAddToLibrary = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(37, 42, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 426));

        lblHome.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblHome.setForeground(new java.awt.Color(223, 224, 224));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblWishlist.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblWishlist.setForeground(new java.awt.Color(223, 224, 224));
        lblWishlist.setText("Wishlist");
        lblWishlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWishlistMouseClicked(evt);
            }
        });

        lblLibrary.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblLibrary.setForeground(new java.awt.Color(223, 224, 224));
        lblLibrary.setText("Library");
        lblLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLibraryMouseClicked(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(223, 224, 224));
        lblProfile.setText("Profile");
        lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfileMouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(245, 83, 112));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout)
                    .addComponent(lblLibrary)
                    .addComponent(lblHome)
                    .addComponent(lblProfile)
                    .addComponent(lblWishlist, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWishlist, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(185, 185, 185)
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jLabel3.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 224, 224));
        jLabel3.setText("Book Detail");

        lblAuthor.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblAuthor.setText("Author Name");

        lblPrice.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblPrice.setText("Book Price");

        jLabel1.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel1.setText("Author");

        jLabel4.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel5.setText("Title");

        lblTitle.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        lblTitle.setText("Book Title");

        btnAddToLibrary.setBackground(new java.awt.Color(64, 206, 206));
        btnAddToLibrary.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnAddToLibrary.setForeground(new java.awt.Color(37, 42, 51));
        btnAddToLibrary.setText("Add to Library");
        btnAddToLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToLibraryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnAddToLibrary))
                .addGap(0, 282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(btnAddToLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToLibraryActionPerformed
        if (isBookPurchased) {
            //redirect to book content
            mainFrame.showView(new ContentView(mainFrame, book));
        } else {
            //add book to library/purchase book->deduct balance if the book is not free
            //then set the isBookPurchased to true then update the button text
            if (book.getPrice() > 0) {
                // if balance < price -> error message
                String bookPrice = Double.toString(book.getPrice());
                int confirm = JOptionPane.showConfirmDialog(this, "Beli buku seharga " + bookPrice + " ?", "Konfirmasi Pembelian", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    if (currentReader.getBalance() >= book.getPrice()) {
                        currentReader.deductBalance(book.getPrice());
                        currentReader.addBookToLibrary(book);
                        JOptionPane.showMessageDialog(this, "Berhasil Menambahkan buku ke Library!");
                        //klo buku yg dibeli ada di wishlist maka dihapus dari wishlist
                        if (currentReader.isBookInWishlist(book)) {
                            currentReader.removeFromWishlist(book);
                        }
                    } else {
                        // duit kurang
                        JOptionPane.showMessageDialog(this, "Saldo Anda tidak mencukupi.", "Saldo Kurang", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                //buku gratis langsung add to library
                currentReader.addBookToLibrary(book);
                JOptionPane.showMessageDialog(this, "Berhasil Menambahkan buku ke Library!");
                // klo bukunya ada di wishlist, dihapus dari wishlist
                if (currentReader.isBookInWishlist(book)) {
                    currentReader.removeFromWishlist(book);
                }
            }
            isBookPurchased = setButtonAction();
        }
    }//GEN-LAST:event_btnAddToLibraryActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Logout
            mainFrame.showView(mainFrame.getLoginView());
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        mainFrame.showView(new ReaderHomeView(mainFrame));
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblWishlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWishlistMouseClicked
        mainFrame.showView(new WishlistView(mainFrame));
    }//GEN-LAST:event_lblWishlistMouseClicked

    private void lblLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLibraryMouseClicked
        mainFrame.showView(new LibraryView(mainFrame));
    }//GEN-LAST:event_lblLibraryMouseClicked

    private void lblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfileMouseClicked
        mainFrame.showView(new ReaderProfileView(mainFrame));
    }//GEN-LAST:event_lblProfileMouseClicked

    private boolean setButtonAction() {
        if (currentReader.isBookInLibrary(book)) {
            btnAddToLibrary.setText("Read The Book");
            return true;
        }
        return false;
    }

    private void setDetailTextFields() {
        lblTitle.setText(book.getTitle());
        lblAuthor.setText(book.getAuthor());
        lblPrice.setText(Double.toString(book.getPrice()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToLibrary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblAuthor;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField lblPrice;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JTextField lblTitle;
    private javax.swing.JLabel lblWishlist;
    // End of variables declaration//GEN-END:variables
}
