/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.reader;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Reader;
import models.User;
import services.DatabaseService;
import ui.main.MainFrame;

/**
 *
 * @author Dukhaan
 */
public class ReaderProfileView extends javax.swing.JPanel {

    /**
     * Creates new form ProfileReaderView
     */
    private MainFrame mainFrame;

    public ReaderProfileView(MainFrame mainFrame) {
        initComponents();
        lblSaldo.setEditable(false);
        this.mainFrame = mainFrame;

        // Buat nge-trigger lblSaldo nampilin current balance
        lblSaldoActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblWishlist = new javax.swing.JLabel();
        lblLibrary = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdateProfile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTopUp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnTopUp = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(37, 42, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 426));

        lblHome.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblHome.setForeground(new java.awt.Color(223, 224, 224));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblWishlist.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblWishlist.setForeground(new java.awt.Color(223, 224, 224));
        lblWishlist.setText("Wishlist");
        lblWishlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWishlistMouseClicked(evt);
            }
        });

        lblLibrary.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblLibrary.setForeground(new java.awt.Color(223, 224, 224));
        lblLibrary.setText("Library");
        lblLibrary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLibraryMouseClicked(evt);
            }
        });

        lblProfile.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(223, 224, 224));
        lblProfile.setText("Profile");

        lblLogout.setFont(new java.awt.Font("Sora", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(245, 83, 112));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout)
                    .addComponent(lblLibrary)
                    .addComponent(lblHome)
                    .addComponent(lblProfile)
                    .addComponent(lblWishlist, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWishlist, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(190, 190, 190)
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jLabel3.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 224, 224));
        jLabel3.setText("Profile");

        lblName.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N

        lblUsername.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel1.setText("Name");

        jLabel4.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel4.setText("Username");

        btnUpdateProfile.setBackground(new java.awt.Color(64, 206, 206));
        btnUpdateProfile.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnUpdateProfile.setForeground(new java.awt.Color(37, 42, 51));
        btnUpdateProfile.setText("Update");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel5.setText("Password");

        lblPassword.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N

        lblSaldo.setFont(new java.awt.Font("Sora", 1, 18)); // NOI18N
        lblSaldo.setText("Rp");
        lblSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSaldoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 224, 224));
        jLabel7.setText("Saldo");

        jLabel2.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel2.setText("Saldo Kamu");

        lblTopUp.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel6.setText("Top Up Saldo");

        btnTopUp.setBackground(new java.awt.Color(255, 167, 117));
        btnTopUp.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        btnTopUp.setForeground(new java.awt.Color(37, 42, 51));
        btnTopUp.setText("Top Up");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProfile)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(lblTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTopUp))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSaldo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopUp)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        String newName = lblName.getText();
        String newUsername = lblUsername.getText();
        String newPassword = lblPassword.getText();

        User currentUser = DatabaseService.getCurrentUser();

        // Mendapatkan referensi objek User yang ingin diubah (misalnya, user yang sedang login)
        if (currentUser != null) {
            // Mengubah data pengguna sesuai input yang diberikan
            currentUser.setName(newName);
            currentUser.setUsername(newUsername);
            currentUser.setPassword(newPassword);

            // Memperbarui tampilan atau melakukan tindakan lain yang diperlukan setelah pembaruan
            updateUI();

            JOptionPane.showMessageDialog(this, "Data user berhasil diperbarui!");
            mainFrame.showView(mainFrame.getLoginView());
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada pengguna yang aktif.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        mainFrame.showView(new ReaderHomeView(mainFrame));
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblWishlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWishlistMouseClicked
        mainFrame.showView(new WishlistView(mainFrame));
    }//GEN-LAST:event_lblWishlistMouseClicked

    private void lblLibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLibraryMouseClicked
        mainFrame.showView(new LibraryView(mainFrame));
    }//GEN-LAST:event_lblLibraryMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Logout
            mainFrame.showView(mainFrame.getLoginView());
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    // Nampilin current saldo
    private void lblSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSaldoActionPerformed
        User currentUser = DatabaseService.getCurrentUser();

        if (currentUser instanceof Reader) {
            // Mengambil referensi ke objek Reader
            Reader currentReader = (Reader) currentUser;

            // Memanggil metode getBalance dari objek Reader
            double balance = currentReader.getBalance();

            // Mengisi nilai pada field lblSaldo dengan nilai saldo
            lblSaldo.setText("Rp " + String.valueOf(balance));
        } else {
            // Tampilkan pesan kesalahan jika pengguna yang login bukan objek dari kelas Reader
            JOptionPane.showMessageDialog(this, "Anda bukan pembaca (Reader).");
        }
    }//GEN-LAST:event_lblSaldoActionPerformed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        String inputtedSaldo = lblTopUp.getText();

        try {
            // Mengubah nilai saldo dari string ke double
            double saldoTopUp = Double.parseDouble(inputtedSaldo);

            // Mendapatkan pengguna yang sedang login
            User currentUser = DatabaseService.getCurrentUser();

            if (currentUser instanceof Reader) {
                // Mengambil referensi ke objek Reader
                Reader currentReader = (Reader) currentUser;

                // Melakukan top-up saldo dengan metode addBalance
                currentReader.addBalance(saldoTopUp);

                // Memanggil metode updateUI untuk memperbarui tampilan
                updateUI();

                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(this, "Top-up saldo berhasil dilakukan!");
            } else {
                // Tampilkan pesan kesalahan jika pengguna yang login bukan objek dari kelas Reader
                JOptionPane.showMessageDialog(this, "Anda bukan pembaca (Reader).");
            }
        } catch (NumberFormatException e) {
            // Menangani kesalahan jika input tidak valid
            JOptionPane.showMessageDialog(this, "Input tidak valid. Masukkan nominal top-up yang benar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTopUpActionPerformed

    public void updateUI() {
        SwingUtilities.invokeLater(() -> {
            lblName.setText(DatabaseService.getCurrentUser().getName());
            lblUsername.setText(DatabaseService.getCurrentUser().getUsername());
            lblPassword.setText(DatabaseService.getCurrentUser().getPassword());
            lblTopUp.setText("");

            if (DatabaseService.getCurrentUser() instanceof Reader) {
                Reader currentReader = (Reader) DatabaseService.getCurrentUser();
                lblSaldo.setText("Rp " + String.valueOf(currentReader.getBalance()));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTopUp;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField lblName;
    private javax.swing.JTextField lblPassword;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JTextField lblSaldo;
    private javax.swing.JTextField lblTopUp;
    private javax.swing.JTextField lblUsername;
    private javax.swing.JLabel lblWishlist;
    // End of variables declaration//GEN-END:variables
}
