/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.auth;

import java.util.List;
import javax.swing.JOptionPane;
import models.Admin;
import models.Reader;
import models.User;
import services.DatabaseService;
import ui.admin.AdminHomeView;
import ui.main.MainFrame;
import ui.reader.ReaderHomeView;

/**
 *
 * @author Dukhaan
 */
public class LoginView extends javax.swing.JPanel {

    /**
     * Creates new form LoginView
     */
    private User user;
    private MainFrame mainFrame;
    List<User> daftarUser;

    public LoginView(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Sora", 1, 20)); // NOI18N
        jLabel2.setText("Login");

        id.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jLabel3.setText("Password");

        pass.setFont(new java.awt.Font("Sora", 0, 10)); // NOI18N

        btnLogin.setBackground(new java.awt.Color(64, 206, 206));
        btnLogin.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(46, 52, 64));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(46, 52, 64));
        btnRegister.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(223, 224, 224));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = this.id.getText();
        String pass = this.pass.getText();

        if (username.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Nama pengguna dan kata sandi harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // get all registered users
            daftarUser = DatabaseService.getAllUsers();
            // loop through registered users and check for credentials
            User loggedInUser = null;
            for (User user : daftarUser) {
                if (user.login(username, pass)) {
                    // if found one, get the user and exit loop
                    loggedInUser = user;
                    break;
                }
            }

            // if somehow cannot found registered user, prompt them
            if (loggedInUser == null) {
                JOptionPane.showMessageDialog(this, "Tidak bisa menemukan user!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // set pengguna yang sedang aktif setelah autentikasi berhasil
                DatabaseService.setCurrentUser(loggedInUser);
                JOptionPane.showMessageDialog(this, "Berhasil Login!");

                // check for user types
                if (loggedInUser instanceof Reader) {
                    // if user is reader, redirect to reader home view
                    mainFrame.showView(new ReaderHomeView(mainFrame));
                } else if (loggedInUser instanceof Admin) {
                    // if user is admin, redirect to admin home view
                    mainFrame.showView(new AdminHomeView(mainFrame));
                } else {
                    // TODO: handle user with no user type
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        mainFrame.showView(new RegisterView(mainFrame));
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
